twitter/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from app.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', Dashboard.as_view()),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login_user.html')),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/')),
    path('accounts/profile/', Dashboard.as_view()),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_change_form.html')),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html')),
    path('user/<int:id>/', UserView.as_view()),
    path('user/details/', UserDetails.as_view()),
    path('received/', Received.as_view()),
    path('sent/', Sent.as_view()),
    path('send_message/', SendMessage.as_view()),
    path('delete_confirm/', DeleteUserConfirm.as_view(), name='delete_account'),
    path('delete_account/', DeleteUser.as_view()),
    path('settings/', Settings.as_view(), name='settings'),
    path('change_username/', Dashboard.as_view(), name='change_username'),
    path('change_email/', Dashboard.as_view(), name='change_email'),
    path('new_tweet/', NewTweet.as_view()),
    path('delete_tweet/<int:id>/', DeleteTweet.as_view()),
    path('add_comment/', AddCommentView.as_view(), name='add-comment')

]

app/models.py
from django.contrib.auth.models import User
from django.db import models


class Tweet(models.Model):
    message = models.CharField(max_length=140)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Comment(models.Model):
    message = models.CharField(max_length=60)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)


class Message(models.Model):
    sender = models.ForeignKey(User, related_name='sender', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='receiver', on_delete=models.CASCADE)
    text = models.TextField()

app/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.forms import ModelForm
from app.models import *
from django import forms


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', "password1", "password2")


class LoginUserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class ChangePasswordForm(PasswordChangeForm):
    class Meta:
        model = User


class SendMessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['sender', 'receiver', 'text']
        widgets = {'text': forms.Textarea(attrs={'cols': 80, 'rows': 7}),
                   'sender': forms.HiddenInput()}


class NewTweetForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ['message', 'user']
        widgets = {'user': forms.HiddenInput()}

app/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from app.forms import RegisterUserForm, SendMessageForm, NewTweetForm
from app.models import *



''' ################# MAINS VIEW ######################'''

'''
Dashboard with all tweets from database
'''

class Dashboard(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        tweets = Tweet.objects.all()
        return render(request, 'dashboard.html', {'tweets': tweets})


'''View with all yours tweets'''


class UserView(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request, id):
        tweets = Tweet.objects.filter(user=id)
        return render(request, 'user.html', {'tweets': tweets})


''' ################# COMMENTS ######################'''


'''Adding comments view, you can add'''


class AddCommentView(LoginRequiredMixin, View):
    login_url = '/login/'

    def post(self, request):
        user = User.objects.get(id=request.POST.get('user'))
        tweet = Tweet.objects.get(id=request.POST.get('tweet'))
        message = request.POST.get('message')
        next = request.POST.get('next')

        if user and tweet and message:
            Comment.objects.create(tweet=tweet,
                                   message=message,
                                   user=user)
        return redirect(next)


''' ################# USERS ######################'''


'''Register user view'''

class RegisterView(View):

    def get(self, request):
        form = RegisterUserForm()
        return render(request, 'register_user.html', {'form': form})

    def post(self, request):
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            User.objects.create_user(username=form.cleaned_data['email'],
                                     password=form.cleaned_data['password1'],
                                     email=form.cleaned_data['email'])
            user = authenticate(request,
                                username=form.cleaned_data['email'],
                                password=form.cleaned_data['password1'])
            login(request, user)
            return redirect('/dashboard/')
        return redirect('/register_user/')


'''Deletion user confirmation view'''


class DeleteUserConfirm(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        return render(request, 'delete_user.html')


'''Deletion user view'''


class DeleteUser(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        user = User.objects.get(id=request.user.pk)
        user.delete()
        return redirect('/login/')


'''User details view'''


class UserDetails(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        return render(request, 'user_details.html')


''' User settings view'''


class Settings(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        return render(request, 'settings.html')


''' ################# MESSAGES ######################'''


'''Received emails'''


class Received(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        received = Message.objects.filter(receiver=request.user.pk)
        return render(request, 'received.html', {'received': received})


'''Sent emails'''


class Sent(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        sent = Message.objects.filter(sender=request.user.pk)
        return render(request, 'sent.html', {'sent': sent})


'''New message form'''


class SendMessage(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        form = SendMessageForm(initial={'sender': request.user})
        return render(request, 'new_message.html', {'form': form})

    def post(self, request):
        form = SendMessageForm(request.POST, initial={'sender': request.user})
        if form.is_valid():
            form.save()
            return redirect('/received/')
        return redirect('/dashboard/')


''' ################# TWEET ######################'''

'''Create new Tweet form'''


class NewTweet(View):

    def get(self, request):
        form = NewTweetForm(initial={'user': request.user})
        return render(request, 'new_tweet.html', {'form': form})

    def post(self, request):
        form = NewTweetForm(request.POST, initial={'user': request.user})
        if form.is_valid():
            form.save()
            return redirect(f'/user/{request.user.pk}')
        return redirect(f'/new_tweet/')


'''Delete tweet form'''


class DeleteTweet(View):

    def get(self, request, id):
        tweet = Tweet.objects.get(id=id)
        tweet.delete()
        return redirect(f'/user/{request.user.pk}')

app/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <!-- For Google -->
    <link rel="author" href="https://plus.google.com/+Scoopthemes">
    <link rel="publisher" href="https://plus.google.com/+Scoopthemes">
    <!-- for Twitter -->
    <meta name="twitter:card" content="photo">
    <meta name="twitter:site" content="">
    <meta name="twitter:title" content="">
    <meta name="twitter:description" content="">
    <meta name="twitter:image" content="">
    <meta name="twitter:url" content="">
    <!-- for Facebook OpenGraph -->
    <meta property="og:title" content=""/>
    <meta property="og:type" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:description" content=""/>

    <!-- Canonical -->
    <link rel="canonical" href="">

    <title>Sidebar Layout - Scoop Themes Template</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <!-- font Awesome CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

    <!-- Main Styles CSS -->
    <link href="{% static "css/main.css" %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <style>p : {
        border-style: double;
    }</style>
    <![endif]-->

</head>

<body>

<div id="wrapper">

    <aside id="sideBar">
        <ul class="main-nav">
            <!-- Your Logo Or Site Name -->
            <li class="nav-brand">
                <a href="#"><img src="{% static "img/logo2.jpg" %}" alt="" width="200" height="50"></a>
            </li>
            <li>
                <a href="/dashboard/">- Dashboard</a>
            </li>
            <li>
                <a href="/user/{{ user.id }}/">- Yours Tweets</a>
            </li>
            <li>
                <a href="/user/details/">- Account</a>
            </li>
            <li>
                <a href="/received/">- Messages</a>
            </li>
            <li>
                <a href="{% url "settings" %}">- Settings</a>
            </li>
        </ul>

        <p>
            {% if user.is_authenticated %}
                {{ user }}<br>
                <a href="/logout">Logout</a>
            {% else %}
                Please
                <a href="/logout">Log in</a>
            {% endif %}
        </p>

    </aside>

    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            <h1>Ćwierkacz app</h1>
            <p>By <a href="http://linkedin.com/in/maciej-witos">Maciej Witos</a> using Django 2.2.7 as WorkShop based on
                Bootstrap 3.3.0 | <a href="http://github.com/maciejwitos/"> GitHub</a></p>

            <div class="form-group">
                <button id="menuToggler" class="btn btn-primary">Menu</button>
            {% if user.is_authenticated %}
                    <button class="btn btn-primary"><a href="/new_tweet/" style="color: snow">Creat New Tweet</a></button>
            {% endif %}
            </div>

            <section>
                {% block content %}

                {% endblock %}
            </section>
        </div>

    </section>


</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

<!-- Bootstrap JavaScript -->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

<!-- Custom JavaScript -->
<script src="{% static "js/custom.js" %}"></script>

<!-- Call functions on document ready -->
<script>
    $(document).ready(function () {
        // Call Menu Toggler
        appMaster.menuToggler();
        // Example Call anotherFunction
        appMaster.anotherFunction();
    });
</script>

</body>

</html>

app/templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
    <section>
        {% for tweet in tweets %}
            <hr>
            <hr>
            <div>
                <p>@{{ tweet.user }}
                <p>{{ tweet.message }}<p>
            </p>
                <hr>
                Komentarze
                {% for coment in tweet.comment_set.all %}
                    <p>@{{ coment.user }}</p>
                    <p>{{ coment.message }}</p>
                {% endfor %}
              <form action="/add_comment/" method="post">
                    {% csrf_token %}
                    <input type="text" name="message">
                    <input type="hidden" value="{{ user.id }}" name="user">
                    <input type="hidden" value="{{ tweet.id }}" name="tweet">
                    <input type="hidden" value="{{ request.path }}" name="next">
                    <input type="submit" value="Comment">
                </form>
            </div>
        {% endfor %}
    </section>
{% endblock %}

app/templates/delete_user.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <p>Do you want delete your account?</p>
        <p><a href="/delete_account/">Delete</a></p>
    </div>
{% endblock %}

app/templates/login_user.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p><p><a href="{% url "register" %}">Register</a></p>

{% endblock %}

app/templates/new_message.html
{% extends 'base.html' %}
{% block content %}
    <form action="/send_message/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">
    </form>
{% endblock %}

app/templates/new_tweet.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Tweet it!">
    </form>
{% endblock %}

app/templates/password_change_done.html
{% extends "base.html" %}

{% block content %}
<p>Password changed successfully</p>
    <p><a href="/dashboard/">Back to Dahsboard</a></p>

{% endblock %}

app/templates/password_change_form.html
{% extends "base.html" %}

{% block content %}
<form action="/password_change/" method="post">
{% csrf_token %}
{{ form }}
<input type="submit" value="Change password">
</form>


{% endblock %}

app/templates/received.html
{% extends 'base.html' %}
{% block content %}
    <h1>Received</h1>
    <h3><a href="/received/">Received  |</a><a href="/sent/">   Sent  |</a><a href="/send_message/">   New Message |</a></h3>
    <div style="border-style: dot-dash; border-width: 4px; color: #4f4f4f">
        {% for message in received %}
            <p style="border: #4f4f4f">Sender:{{ message.sender }}, Receiver: {{ message.receiver }}</p>
            <p>{{ message.text }}</p>
            <hr>
        {% endfor %}
    </div>
{% endblock %}

app/templates/register_user.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
        {{ form }}
        <input type="submit" value="Zarejestruj">
    </form>
{% endblock %}

app/templates/sent.html
{% extends 'base.html' %}
{% block content %}
    <h1>Sent</h1>
    <h3><a href="/received/">Received  |</a><a href="/sent/">   Sent  |</a><a href="/send_message/">   New Message |</a></h3>
   <div style="border-style: dot-dash; border-width: 4px; color: #4f4f4f">
        {% for message in sent %}
            <p style="border: #4f4f4f">Sender: {{ message.sender }}, Receiver: {{ message.receiver }}</p>
            <p>{{ message.text }}</p>
            <hr>
        {% endfor %}
    </div>
{% endblock %}

app/templates/settings.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        <li><a href="{% url "change_username" %}">Change username</a></li>
        <li><a href="/password_change/">Change password</a></li>
        <li><a href="{% url "change_email" %}">Change email</a></li>
        <li><a href="{% url "delete_account" %}">Delete account</a></li>
    </ul>
{% endblock %}

app/templates/user.html
{% extends 'base.html' %}
{% block content %}
    <section>
        {% for tweet in tweets %}
            <hr>
            <hr>
            <div>
                <p>@{{ tweet.user }}
                <p>{{ tweet.message }}<p>
                <input type="hidden" value="{{ tweet }}" name="tweet_name">
                <a href="/delete_tweet/{{ tweet.id }}/">Delete</a>
            </p>
                <p>
                <hr>
                Komentarze
                {% for coment in tweet.comment_set.all %}
                    <p>@{{ coment.user }}</p>
                    <p>{{ coment.message }}</p>
                {% endfor %}
                <form action="/add_comment/" method="post">
                    {% csrf_token %}
                    <input type="text" name="message">
                    <input type="hidden" value="{{ user.id }}" name="user">
                    <input type="hidden" value="{{ tweet.id }}" name="tweet">
                    <input type="hidden" value="{{ request.path }}" name="next">
                    <input type="submit" value="Comment">
                </form>
            </div>
        {% endfor %}
    </section>
{% endblock %}

app/templates/user_details.html
{% extends 'base.html' %}
{% block content %}
    <table border="1">
        <tr>
            <td>UserName</td>
            <td>{{ user.username }}</td>
            <td></td>
        </tr>

        <tr>
            <td>Email</td>
            <td>{{ user.email }}</td>
            <td><a href="/change_email/">Change email</a></td>
        </tr>
        <tr>
            <td>Password</td>
            <td>{{ user.password }}</td>
            <td><a href="/change_password/">Change password</a></td>
        </tr>
        <tr>
            <td>Tweets</td>
            <td>{{ user.tweet_set.all.count }}</td>
            <td><a href="/new_tweet/">Creat New Tweet</a></td>
        </tr>
    </table>
{% endblock %}